-- Games & Bets schema for BIG MONEY GAMING
-- Run this SQL in Supabase SQL Editor

-- 1) GAMES TABLE
CREATE TABLE IF NOT EXISTS public.games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,                 -- e.g. "Chiefs vs Bills"
  team1 TEXT NOT NULL,
  team2 TEXT NOT NULL,
  league TEXT,
  status TEXT NOT NULL DEFAULT 'upcoming',   -- 'upcoming' | 'live' | 'finished'
  game_start_at TIMESTAMPTZ,                -- actual game start time
  campaign_start_at TIMESTAMPTZ,            -- when betting campaign opens
  campaign_end_at TIMESTAMPTZ,              -- when betting campaign closes
  winner TEXT,                              -- 'team1' | 'team2' | 'draw' | null
  finished_at TIMESTAMPTZ,                  -- when game was finished and winner declared
  created_by BIGINT,                        -- users.id of super_admin who created it
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_games_status ON public.games(status);
CREATE INDEX IF NOT EXISTS idx_games_campaign_window ON public.games(campaign_start_at, campaign_end_at);

-- updated_at trigger
CREATE OR REPLACE FUNCTION public.update_games_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_games_updated_at ON public.games;
CREATE TRIGGER trg_update_games_updated_at
  BEFORE UPDATE ON public.games
  FOR EACH ROW
  EXECUTE FUNCTION public.update_games_updated_at();


-- 2) BETS TABLE
CREATE TABLE IF NOT EXISTS public.bets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  game_id BIGINT NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
  bet_on TEXT NOT NULL CHECK (bet_on IN ('team1', 'team2')),
  amount NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'won', 'lost', 'cancelled')),
  payout NUMERIC(10,2),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bets_user_id ON public.bets(user_id);
CREATE INDEX IF NOT EXISTS idx_bets_game_id ON public.bets(game_id);
CREATE INDEX IF NOT EXISTS idx_bets_status ON public.bets(status);


-- 3) RLS POLICIES

-- Enable RLS
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bets ENABLE ROW LEVEL SECURITY;

-- Helper expressions:
--   auth.jwt()->'user_metadata'->>'role'      : 'user' | 'super_admin'
--   auth.jwt()->'user_metadata'->>'user_id'   : users.id (string)

-- GAMES: Everyone can SELECT
DROP POLICY IF EXISTS games_select_all ON public.games;
CREATE POLICY games_select_all
ON public.games
FOR SELECT
TO public
USING (true);

-- GAMES: Only super_admin can INSERT/UPDATE/DELETE
DROP POLICY IF EXISTS games_super_admin_write ON public.games;
CREATE POLICY games_super_admin_write
ON public.games
FOR ALL
TO public
USING ( (auth.jwt()->'user_metadata'->>'role') = 'super_admin' )
WITH CHECK ( (auth.jwt()->'user_metadata'->>'role') = 'super_admin' );


-- BETS: Users can see only their own bets
DROP POLICY IF EXISTS bets_select_own ON public.bets;
CREATE POLICY bets_select_own
ON public.bets
FOR SELECT
TO public
USING ( user_id = (auth.jwt()->'user_metadata'->>'user_id')::bigint );

-- BETS: Super admin can see all bets
DROP POLICY IF EXISTS bets_select_super_admin ON public.bets;
CREATE POLICY bets_select_super_admin
ON public.bets
FOR SELECT
TO public
USING ( (auth.jwt()->'user_metadata'->>'role') = 'super_admin' );

-- BETS: Users can place bets only during campaign window of the game
DROP POLICY IF EXISTS bets_insert_campaign_window ON public.bets;
CREATE POLICY bets_insert_campaign_window
ON public.bets
FOR INSERT
TO public
WITH CHECK (
  user_id = (auth.jwt()->'user_metadata'->>'user_id')::bigint
  AND EXISTS (
    SELECT 1 FROM public.games g
    WHERE g.id = bets.game_id
      AND g.campaign_start_at IS NOT NULL
      AND g.campaign_end_at IS NOT NULL
      AND NOW() BETWEEN g.campaign_start_at AND g.campaign_end_at
  )
);

-- BETS: Only super_admin can update/cancel bets (e.g. after game finishes)
DROP POLICY IF EXISTS bets_update_super_admin ON public.bets;
CREATE POLICY bets_update_super_admin
ON public.bets
FOR UPDATE
TO public
USING ( (auth.jwt()->'user_metadata'->>'role') = 'super_admin' )
WITH CHECK ( (auth.jwt()->'user_metadata'->>'role') = 'super_admin' );


-- 4) PERMISSIONS
GRANT SELECT, INSERT, UPDATE, DELETE ON public.games TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.bets TO anon, authenticated;


-- 5) OPTIONAL: MARK A SUPER ADMIN (run once, replace username)
-- UPDATE public.users SET role = 'super_admin' WHERE username = 'your_admin_username';


