-- Migration script: Update existing users table OR create new one
-- Run this SQL in your Supabase SQL Editor

-- Step 1: Check if table exists and has email column, then migrate
DO $$
BEGIN
    -- Check if users table exists
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'users') THEN
        -- Table exists, check if it has email column (old schema)
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'email') THEN
            -- Old schema detected - migrate to new schema
            RAISE NOTICE 'Migrating existing users table from email to username...';
            
            -- Add username column if it doesn't exist
            IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'username') THEN
                ALTER TABLE users ADD COLUMN username VARCHAR(255);
                
                -- Migrate email to username (use email as username for existing users)
                UPDATE users SET username = LOWER(SPLIT_PART(email, '@', 1)) WHERE username IS NULL;
                
                -- Make username NOT NULL after migration
                ALTER TABLE users ALTER COLUMN username SET NOT NULL;
                
                -- Add unique constraint on username
                CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_unique ON users(username);
            END IF;
            
            -- Drop email column if it exists
            IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'email') THEN
                ALTER TABLE users DROP COLUMN email;
            END IF;
            
            RAISE NOTICE 'Migration completed!';
        ELSE
            -- Table exists but no email column - might already be migrated or have different schema
            RAISE NOTICE 'Users table exists but no email column found. Checking for username...';
            
            -- Ensure username column exists
            IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'username') THEN
                ALTER TABLE users ADD COLUMN username VARCHAR(255) UNIQUE NOT NULL;
            END IF;
        END IF;
    ELSE
        -- Table doesn't exist - create new one
        RAISE NOTICE 'Creating new users table...';
        
        CREATE TABLE users (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          username VARCHAR(255) UNIQUE NOT NULL,
          password_hash TEXT NOT NULL,
          name VARCHAR(255) NOT NULL,
          role TEXT NOT NULL DEFAULT 'user',
          created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
        
        RAISE NOTICE 'New users table created!';
    END IF;
END $$;

-- Step 2: Ensure all required columns exist
DO $$
BEGIN
    -- Add name column if missing
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'name') THEN
        ALTER TABLE users ADD COLUMN name VARCHAR(255) NOT NULL DEFAULT '';
    END IF;
    
    -- Remove phone column if it exists (no longer needed)
    IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'phone') THEN
        ALTER TABLE users DROP COLUMN phone;
    END IF;
    
    -- Add password_hash column if missing
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'password_hash') THEN
        ALTER TABLE users ADD COLUMN password_hash TEXT NOT NULL DEFAULT '';
    END IF;

    -- Add role column if missing
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'role') THEN
        ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'user';
    END IF;
    
    -- Add created_at if missing
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'created_at') THEN
        ALTER TABLE users ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
    END IF;
    
    -- Add updated_at if missing
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'updated_at') THEN
        ALTER TABLE users ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
    END IF;
END $$;

-- Step 3: Create/update indexes
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);

-- Step 4: Disable RLS (for demo purposes)
ALTER TABLE users DISABLE ROW LEVEL SECURITY;

-- Step 5: Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON users TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON users TO authenticated;

-- Step 6: Create/update trigger for updated_at
CREATE OR REPLACE FUNCTION update_users_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at 
    BEFORE UPDATE ON users 
    FOR EACH ROW 
    EXECUTE FUNCTION update_users_updated_at();

-- Step 7: Add comments
COMMENT ON TABLE users IS 'User accounts table with username and password';
COMMENT ON COLUMN users.username IS 'Unique username for login';
COMMENT ON COLUMN users.password_hash IS 'SHA-256 hashed password';
COMMENT ON COLUMN users.name IS 'Full name of the user';
COMMENT ON COLUMN users.role IS 'Role of the user: user or super_admin';

