-- Create registrations table for Super Bowl cashback campaign
-- Run this SQL in your Supabase SQL Editor

-- Create the registrations table
CREATE TABLE registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(20) NOT NULL,
  team VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add indexes for better performance
CREATE INDEX idx_registrations_email ON registrations(email);
CREATE INDEX idx_registrations_team ON registrations(team);
CREATE INDEX idx_registrations_created_at ON registrations(created_at);

-- Enable Row Level Security (RLS)
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;

-- Create policies for the registrations table
-- Allow anyone to insert data (for public registration form)
CREATE POLICY "Allow public insert" ON registrations
  FOR INSERT WITH CHECK (true);

-- Allow service role to read all data (for admin purposes)
CREATE POLICY "Allow service role read all" ON registrations
  FOR SELECT USING (auth.role() = 'service_role');

-- Allow service role to update all data
CREATE POLICY "Allow service role update all" ON registrations
  FOR UPDATE USING (auth.role() = 'service_role');

-- Allow service role to delete all data
CREATE POLICY "Allow service role delete all" ON registrations
  FOR DELETE USING (auth.role() = 'service_role');

-- Add comments for documentation
COMMENT ON TABLE registrations IS 'Super Bowl cashback campaign registrations';
COMMENT ON COLUMN registrations.name IS 'Full name of the registrant';
COMMENT ON COLUMN registrations.email IS 'Email address (unique identifier)';
COMMENT ON COLUMN registrations.phone IS 'Phone number for contact';
COMMENT ON COLUMN registrations.team IS 'Chosen Super Bowl team (chiefs or eagles)';
COMMENT ON COLUMN registrations.created_at IS 'Registration timestamp';
COMMENT ON COLUMN registrations.updated_at IS 'Last update timestamp';

-- Create a function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_registrations_updated_at 
    BEFORE UPDATE ON registrations 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Optional: Create a view for easy querying of recent registrations
CREATE VIEW recent_registrations AS
SELECT 
    name,
    email,
    phone,
    team,
    created_at
FROM registrations 
ORDER BY created_at DESC 
LIMIT 100;

-- Grant necessary permissions
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON registrations TO authenticated;
GRANT INSERT ON registrations TO anon;
GRANT SELECT ON recent_registrations TO authenticated;
